---
- name: Import base system setup tasks
  import_tasks: setup.yml
  tags: pihole_setup

- name: Import Docker container deployment tasks
  import_tasks: deploy_containers.yml
  tags: pihole_deploy_containers
