# group_vars/all.yml

# --- Plain text variables ---
# Example: Define a common user for your homelab
homelab_user: tim

# Define the base directory for your Docker configs
docker_config_directory: /docker
data_directory: /data

# --- Vaulted variables ---
pihole_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32366634656262396166366365333930353939396364656535636333613163623761643936653762
          6362633966613632343364613933366530373133646362370a356364623239666364626634646364
          62656539646532636434616363653764626234323437373963396633623531306464323430383534
          3365383063616235630a343738393138376266656165323262316162326662326133343335306563
          38383865653564323739373738356634303532313135346338313838646634633437616666313064
          3636626538636531633965393735353265653861313065373031

valheim_server_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31623434643761636235366335313531313037316233343139306361376462373230613165633333
          3537356363333332653135343333373231666533663134620a663162613139623334613338336637
          63326562386661313433663861663739343139306265323162383238313939356437383162636535
          3964343661343462320a656333353531396531383637396134373163373532393330346533336439
          64643232636631623037633865666135626563306562303762353837313364343732393961333564
          6562346338363437346639363733376633313231373933656566

immich_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62333730343434636633306637346230353439343930376235316165373033396237656132313939
          3337643835396134303138326337333062366134663235620a663538353531346466316130633435
          65336335303737326430333732623834386462626133326265323464636332643836393537633536
          3535653963373739610a343164373861646433663663643062313832633831376435323361613732
          65636336393266633761633565323361656365363162353134646265613961306263616436616365
          66653336633039316266623365626563373337663463306166323936623933633337623539636234
          35393335346136616165376234386562366265656236393233653338643234353536303536356434
          61386565623333356239
