---
- name: Configure Pihole lxc
  hosts: pihole_lxc
  become: true
  roles:
    - pihole_lxc

- name: Configure Nginx lxc
  hosts: nginx_lxc
  become: true
  roles:
    - nginx_lxc

- name: Configure Storage lxc 
  hosts: storage_lxc 
  become: true
  roles:
    - storage_lxc 

- name: Configure Gameserver VM and Deploy Services
  hosts: gameserver 
  become: true
  roles:
    - gameserver

- name: Configure Immich lxc 
  hosts: immich_lxc 
  become: true
  roles:
    - immich_lxc 

- name: Configure Paperless lxc 
  hosts: paperless_lxc 
  become: true
  roles:
    - paperless_lxc 
