---
- name: Configure Pihole lxc
  hosts: pihole_lxc
  become: true
  roles:
    - pihole_lxc

- name: Configure Nginx lxc
  hosts: nginx_lxc
  become: true
  roles:
    - nginx_lxc

- name: Configure Storage lxc 
  hosts: storage_lxc 
  become: true
  roles:
    - storage_lxc 

- name: Configure Gameserver VM and Deploy Services
  hosts: gameserver 
  become: true
  roles:
    - gameserver

- name: Configure Mediaserver VM and Deploy Services
  hosts: mediaserver
  become: true
  roles:
    - mediaserver

- name: Configure Immich lxc 
  hosts: immich_lxc 
  become: true
  roles:
    - immich_lxc 

- name: Configure Paperless lxc 
  hosts: paperless_lxc 
  become: true
  roles:
    - paperless_lxc 

- name: Configure monitoring lxc 
  hosts: monitoring_lxc
  become: true
  roles:
    - monitoring_lxc

- name: Configure glance lxc 
  hosts: glance_lxc
  become: true
  roles:
    - glance_lxc
